name: Build MAUI Windows App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build for Windows
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '7.0.x'

    - name: Install MAUI Workload
      run: dotnet workload install maui

    - name: Restore dependencies
      run: dotnet restore

    - name: Build project
      run: dotnet build SmartShop.MAUI.sln --configuration Release -f:net7.0-windows

    - name: Publish app
      run: dotnet publish SmartShop.MAUI.sln --configuration Release -f:net7.0-windows --output ./publish

    - name: Upload published app
      uses: actions/upload-artifact@v4
      with:
        name: SmartShop-Windows
        path: ./publish
