name: Build .NET MAUI Windows App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-maui-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x' # Use the latest .NET 9 SDK

      - name: Display .NET SDKs
        run: dotnet --list-sdks

      - name: Install MAUI workload
        run: dotnet workload install maui

      - name: Build MAUI Windows App
        run: dotnet build --configuration Release -f:net7.0-windows
